Repository TeamCARDNA/Cardna-Android, pull requests merged in 2022-06, with the labels that each got.

#119 [FIX] 토큰 재발급 메서드 message -> status_code
  app/src/main/java/org/cardna/presentation/ui/login/view/SplashActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/viewmodel/LoginViewModel.kt
Labels: bug, 🌈 JongChan

#121 친구액티비티 다이얼로그 color -> white_3 -> white_4
  app/src/main/java/org/cardna/presentation/ui/maincard/view/MainCardActivity.kt
Labels: bug, 🌈 JongChan

#122 로그인 액티비티 -> 카드나 로고 변경
  app/src/main/res/drawable/ic_cardna_logo.xml
  app/src/main/res/layout/activity_login.xml
Labels: 🌈 JongChan

#123 [HOTFIX] QA 이후 할 것
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardCreateActivity.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/java/org/cardna/presentation/ui/setting/view/SecessionActivity.kt
  app/src/main/java/org/cardna/presentation/ui/setting/view/SettingActivity.kt
  app/src/main/java/org/cardna/presentation/ui/setting/viewmodel/SettingViewModel.kt
  app/src/main/res/drawable/bg_cursor_color.xml
  app/src/main/res/layout/activity_card_create.xml
  app/src/main/res/layout/activity_secession.xml
Labels: Minwoo🥺, Complete

#124 [HOTFIX] 친구 코드검색 에러수정, 메인카드 엠티뷰 수정, 카카오로그인 이미지 교체
  app/src/main/java/org/cardna/presentation/ui/cardpack/viewmodel/CardPackViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/SplashActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/viewmodel/LoginViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/view/MainCardFragment.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/viewmodel/MainCardViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/view/SearchFriendCodeActivity.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/res/drawable-xxhdpi/img_login_kakao.9.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_main_card.xml
Labels: DaBin😎, Complete

#125 [RRFACTOR] 애니메이션 시간 단축
  app/src/main/java/org/cardna/presentation/ui/login/view/SetNameActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/SetNameFinishedActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/SplashActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/viewmodel/LoginViewModel.kt
  app/src/main/res/layout/activity_set_name_finished.xml
Labels: bug

#126 [HOTFIX] 앱 업데이트 로직 구현
  app/build.gradle
  app/src/main/java/org/cardna/presentation/base/BaseViewUtil.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/SplashActivity.kt
  app/src/main/java/org/cardna/presentation/ui/setting/view/VersionInfoActivity.kt
  app/src/main/res/layout/activity_version_info.xml
Labels: Minwoo🥺, Complete

#132 [HOTFIX] 네이버로그인 회원가입 오류 해결
  app/src/main/java/org/cardna/presentation/ui/login/view/LoginActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/SetNameActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/viewmodel/LoginViewModel.kt
Labels: Complete

#133 릴리즈 버전
  app/build.gradle
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/BottomDialogImageFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardCreateActivity.kt
  app/src/main/res/layout/activity_edit_card.xml
  app/src/main/res/layout/activity_search_friend_code.xml
  app/src/main/res/layout/dialog_main_card_block.xml
  app/src/main/res/layout/dialog_relation.xml
  app/src/main/res/layout/fragment_bottom_dialog_image.xml
  app/src/main/res/layout/fragment_main_card.xml
  app/src/main/res/values/styles.xml
Labels: Complete, 🌈 JongChan
