Repository TeamCARDNA/Cardna-Android, pull requests merged in 2022-03, with the labels that each got.

#2 [Setting] BottomSheet 세팅 및 Hilt 포인트 추가 폴더링
  .gitignore
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/CardNaApplication.kt
  app/src/main/java/org/cardna/MainActivity.kt
  app/src/main/java/org/cardna/data/local/Temp.kt
  app/src/main/java/org/cardna/data/local/sharedpref/CardnaSharedPreference.kt
  app/src/main/java/org/cardna/data/remote/api/Temp.kt
  app/src/main/java/org/cardna/data/remote/datasource/Temp.kt
  app/src/main/java/org/cardna/data/remote/model/Temp.kt
  app/src/main/java/org/cardna/data/repository/Temp.kt
  app/src/main/java/org/cardna/data/sharedpref/CardnaSharedPreference.kt
  app/src/main/java/org/cardna/domain/model/Temp.kt
  app/src/main/java/org/cardna/domain/repository/Temp.kt
  app/src/main/java/org/cardna/presentation/MainActivity.kt
  app/src/main/java/org/cardna/presentation/base/BaseViewUtil.kt
  app/src/main/java/org/cardna/presentation/base/temp.java
  app/src/main/java/org/cardna/presentation/di/ApiModule.kt
  app/src/main/java/org/cardna/presentation/di/DataSourceModule.kt
  app/src/main/java/org/cardna/presentation/di/RepositoryModule.kt
  app/src/main/java/org/cardna/presentation/di/RetrofitModule.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardPackFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/viewmodel/CardPackViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/insight/view/InsightFragment.kt
  app/src/main/java/org/cardna/presentation/ui/insight/viewmodel/InsightViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/view/MainCardFragment.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/viewmodel/MainCardViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/org/cardna/presentation/util/BindingAdapter.kt
  app/src/main/java/org/cardna/presentation/util/ViewExt.kt
  app/src/main/java/org/cardna/util/BindingAdapter.kt
  app/src/main/res/drawable/ic_cardpack_checked.xml
  app/src/main/res/drawable/ic_cardpack_unchecked.xml
  app/src/main/res/drawable/ic_insight_checked.xml
  app/src/main/res/drawable/ic_insight_unchecked.xml
  app/src/main/res/drawable/ic_maincard_checked.xml
  app/src/main/res/drawable/ic_maincard_unchecked.xml
  app/src/main/res/drawable/ic_mypage_checked.xml
  app/src/main/res/drawable/ic_mypage_unchecked.xml
  app/src/main/res/drawable/selector_cardpack.xml
  app/src/main/res/drawable/selector_insight.xml
  app/src/main/res/drawable/selector_maincard.xml
  app/src/main/res/drawable/selector_mypage.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_card_pack.xml
  app/src/main/res/layout/fragment_insight.xml
  app/src/main/res/layout/fragment_main_card.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/menu/menu_bottom_nav.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: DaBin🌼

#5 [DOCS] #4 - PR Template 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Minwoo🥺, Complete

#7 [Layout] 설정, 알림 레이아웃 완성 및 AlarmViewModel생성
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/presentation/base/BaseViewUtil.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/adapter/FriendRequestAdapter.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/adapter/FriendRequestData.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/adapter/WriteCardYouAdapter.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/view/setting/AlarmActivity.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/view/setting/DeveloperInfoActivity.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/view/setting/PrivacyPolicyActivity.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/view/setting/SecessionActivity.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/view/setting/ServiceOperationActivity.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/view/setting/SettingActivity.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/view/setting/VersionInfoActivity.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/viewmodel/AlarmViewModel.kt
  app/src/main/java/org/cardna/presentation/util/HorizontalItemDecorator.kt
  app/src/main/java/org/cardna/presentation/util/ViewExt.kt
  app/src/main/res/drawable/bg_dark_gray_radius_10dp.xml
  app/src/main/res/drawable/bg_mainpurple_maingreen_gradient_radius_5dp.xml
  app/src/main/res/drawable/divider_white_5_1dp.xml
  app/src/main/res/drawable/img_item_friend_request_dummy.9.png
  app/src/main/res/drawable/img_item_friend_write_cardyou_dummy.9.png
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/activity_developer_info.xml
  app/src/main/res/layout/activity_privacy_policy.xml
  app/src/main/res/layout/activity_secession.xml
  app/src/main/res/layout/activity_service_operation.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/activity_version_info.xml
  app/src/main/res/layout/item_alarm_friend_request.xml
  app/src/main/res/layout/item_alarm_write_cardyou.xml
  app/src/main/res/navigation/main_nav.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values-w1240dp/dimens.xml
  app/src/main/res/values-w600dp/dimens.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: DaBin😎, Layout

#8 [Setting] BottomSheet 아이콘 네이밍 변경 및 디자인 수정사항 반영
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/ic_insight_checked.xml
  app/src/main/res/drawable/ic_mypage_checked.xml
  app/src/main/res/drawable/ic_mypage_unchecked.xml
  app/src/main/res/drawable/ic_selector_cardpack.xml
  app/src/main/res/drawable/ic_selector_insight.xml
  app/src/main/res/drawable/ic_selector_maincard.xml
  app/src/main/res/drawable/ic_selector_mypage.xml
  app/src/main/res/menu/menu_bottom_nav.xml
  app/src/main/res/values/dimens.xml
Labels: DaBin😎, Layout

#10 [Feature] Retrofit 세팅 및 DI 모듈 생성
  app/src/main/java/org/cardna/data/local/singleton/CardNaRepository.kt
  app/src/main/java/org/cardna/data/remote/api/Temp.kt
  app/src/main/java/org/cardna/data/remote/api/alarm/AlarmService.kt
  app/src/main/java/org/cardna/data/remote/api/auth/AuthService.kt
  app/src/main/java/org/cardna/data/remote/api/card/CardService.kt
  app/src/main/java/org/cardna/data/remote/api/friend/FriendService.kt
  app/src/main/java/org/cardna/data/remote/api/insight/InsightService.kt
  app/src/main/java/org/cardna/data/remote/api/like/LikeService.kt
  app/src/main/java/org/cardna/data/remote/api/mypage/MyPageService.kt
  app/src/main/java/org/cardna/data/remote/api/user/UserService.kt
  app/src/main/java/org/cardna/data/remote/datasource/Temp.kt
  app/src/main/java/org/cardna/data/remote/datasource/UserDataSource.kt
  app/src/main/java/org/cardna/data/remote/datasource/UserDataSourceImpl.kt
  app/src/main/java/org/cardna/data/remote/model/Temp.kt
  app/src/main/java/org/cardna/data/remote/model/user/RequestDeleteUserData.kt
  app/src/main/java/org/cardna/data/remote/model/user/ResponseDeleteUserData.kt
  app/src/main/java/org/cardna/data/repository/Temp.kt
  app/src/main/java/org/cardna/data/repository/UserRepositoryImpl.kt
  app/src/main/java/org/cardna/domain/repository/Temp.kt
  app/src/main/java/org/cardna/domain/repository/UserRepository.kt
  app/src/main/java/org/cardna/presentation/di/ApiModule.kt
  app/src/main/java/org/cardna/presentation/di/DataSourceModule.kt
  app/src/main/java/org/cardna/presentation/di/RepositoryModule.kt
  app/src/main/java/org/cardna/presentation/di/RetrofitModule.kt
  app/src/main/java/org/cardna/presentation/util/AuthInterceptor.kt
Labels: DaBin😎, Feature🖥, Complete

#19 [Feature] 카드팩프래그먼트 구현
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/CardNaApplication.kt
  app/src/main/java/org/cardna/presentation/MainActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/adapter/CardPackTabLayoutAdapter.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/BottomDialogCardFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/BottomDialogImageFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardCreateActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardMeFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardPackFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardYouFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/FriendCardPackActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/viewmodel/CardPackViewModel.kt
  app/src/main/res/color/selector_cardpack_tab_cardme_text.xml
  app/src/main/res/color/selector_cardpack_tab_cardyou_text.xml
  app/src/main/res/color/sign_in_white_gray.xml
  app/src/main/res/drawable/bg_dark_gray_radius_8dp.xml
  app/src/main/res/drawable/bg_main_black.xml
  app/src/main/res/drawable/bg_radius_8dp_stroke_real_black_2dp.xml
  app/src/main/res/drawable/dummy_img_cardpack_1.9.png
  app/src/main/res/drawable/ic_pencil.xml
  app/src/main/res/drawable/ic_selector_cardpack_tab_cardme.xml
  app/src/main/res/drawable/ic_selector_cardpack_tab_cardme_line.xml
  app/src/main/res/drawable/ic_selector_cardpack_tab_cardyou.xml
  app/src/main/res/drawable/ic_selector_cardpack_tab_cardyou_line.xml
  app/src/main/res/layout/activity_card_create.xml
  app/src/main/res/layout/activity_friend_card_pack.xml
  app/src/main/res/layout/cardpack_custom_tablayout.xml
  app/src/main/res/layout/fragment_bottom_dialog_card.xml
  app/src/main/res/layout/fragment_bottom_dialog_image.xml
  app/src/main/res/layout/fragment_card_me.xml
  app/src/main/res/layout/fragment_card_pack.xml
  app/src/main/res/layout/fragment_card_you.xml
  app/src/main/res/layout/item_cardpack_cardme.xml
  app/src/main/res/layout/item_cardpack_cardyou.xml
Labels: Minwoo🥺, Complete
