Repository TeamCARDNA/Cardna-Android, pull requests merged in 2022-04, with the labels that each got.

#28 [Feature] 마이페이지 empty 뷰 처리, 검색에러 해결 및 상세카드 내꺼일때 공감 눌리는 설정 반영
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/data/remote/model/card/ResponseDetailCardData.kt
  app/src/main/java/org/cardna/presentation/MainActivity.kt
  app/src/main/java/org/cardna/presentation/ui/detailcard/view/DetailCardActivity.kt
  app/src/main/java/org/cardna/presentation/ui/detailcard/viewmodel/DetailCardViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/insight/view/BlindAreaFragment.kt
  app/src/main/java/org/cardna/presentation/ui/insight/view/OpenAreaFragment.kt
  app/src/main/java/org/cardna/presentation/ui/insight/viewmodel/InsightViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/view/SearchFriendCodeActivity.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/org/cardna/presentation/util/BindingAdapter.kt
  app/src/main/res/layout/activity_detail_card.xml
  app/src/main/res/layout/activity_search_friend_code.xml
  app/src/main/res/layout/fragment_blind_area.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_open_area.xml
  app/src/main/res/values/strings.xml
Labels: DaBin😎, Feature🖥, Layout

#32 [Feature] 메인카드 포지션 세팅 및 유지, 마이페이지 코드 리팩토링
  app/src/main/java/org/cardna/presentation/ui/detailcard/view/DetailCardActivity.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/view/MainCardFragment.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/viewmodel/MainCardViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/setting/view/SecessionActivity.kt
  app/src/main/res/layout/activity_detail_card.xml
  app/src/main/res/layout/activity_secession.xml
  app/src/main/res/layout/fragment_main_card.xml
Labels: DaBin😎, Feature🖥, Complete

#35 [Feature] 카드나, 카드너 프래그먼트 구현
  .idea/misc.xml
  app/src/main/java/org/cardna/data/remote/api/card/CardService.kt
  app/src/main/java/org/cardna/data/remote/datasource/CardDataSource.kt
  app/src/main/java/org/cardna/data/remote/datasource/CardDataSourceImpl.kt
  app/src/main/java/org/cardna/data/repository/CardRepositoryImpl.kt
  app/src/main/java/org/cardna/presentation/MainActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/adapter/CardPackMeRecyclerViewAdapter.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/adapter/CardPackYouRecyclerViewAdapter.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardCreateActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardMeFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardPackFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardYouFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/FriendCardPackActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/viewmodel/CardPackViewModel.kt
  app/src/main/res/drawable/bg_stroke_main_green_darker_1dp_radius_45dp.xml
  app/src/main/res/drawable/bg_stroke_main_purple_darker_1dp_radius_45dp.xml
  app/src/main/res/drawable/bg_stroke_white_2_1dp_radius_45dp.xml
  app/src/main/res/drawable/bg_stroke_white_4_1dp_radius_10dp.xml
  app/src/main/res/drawable/ic_empty_add_cardme.xml
  app/src/main/res/drawable/ic_empty_add_cardyou.xml
  app/src/main/res/drawable/ic_pencil_empty.xml
  app/src/main/res/layout/activity_friend_card_pack.xml
  app/src/main/res/layout/fragment_card_me.xml
  app/src/main/res/layout/fragment_card_pack.xml
  app/src/main/res/layout/fragment_card_you.xml
  app/src/main/res/layout/item_cardpack_cardme.xml
  app/src/main/res/layout/item_main_card_view.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Complete

#37 [FIX] 상세카드 색 변경 안되는 부분 수정
  app/src/main/java/org/cardna/presentation/ui/detailcard/view/DetailCardActivity.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/adapter/MainCardAdapter.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/view/MainCardFragment.kt
  app/src/main/res/layout/activity_detail_card.xml
Labels: DaBin😎, Layout

#39 [Feature] ci setting
  app/build.gradle
  app/src/main/java/org/cardna/presentation/di/RetrofitModule.kt
  app/src/main/java/org/cardna/presentation/ui/login/SetNameActivity.kt
  app/src/main/res/layout/activity_set_name.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values-w1240dp/dimens.xml
  app/src/main/res/values-w600dp/dimens.xml
Labels: bug, DaBin😎, Feature🖥, Complete

#41 [Feature] Gson->Moshi migration
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/org/cardna/data/remote/api/friend/FriendService.kt
  app/src/main/java/org/cardna/data/remote/model/friend/RequestAcceptOrDenyFriendData.kt
  app/src/main/java/org/cardna/data/remote/model/friend/RequestApplyOrCancleFriendData.kt
  app/src/main/java/org/cardna/data/remote/model/like/RequestLikeData.kt
  app/src/main/java/org/cardna/data/remote/model/mypage/ResponseMyPageData.kt
  app/src/main/java/org/cardna/presentation/di/ApiModule.kt
  app/src/main/java/org/cardna/presentation/di/RetrofitModule.kt
  app/src/main/java/org/cardna/presentation/di/SerializationModule.kt
  build.gradle
Labels: DaBin😎, Feature🖥, Complete

#43 [Feature] 카드너 보관함 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/data/local/Temp.kt
  app/src/main/java/org/cardna/data/remote/api/card/CardService.kt
  app/src/main/java/org/cardna/data/remote/datasource/CardDataSource.kt
  app/src/main/java/org/cardna/data/remote/datasource/CardDataSourceImpl.kt
  app/src/main/java/org/cardna/data/remote/model/card/ResponseCardYouStoreData.kt
  app/src/main/java/org/cardna/data/remote/model/friend/RequestApplyOrCancleFriendData.kt
  app/src/main/java/org/cardna/data/remote/model/user/RequestDeleteUserData.kt
  app/src/main/java/org/cardna/data/repository/CardRepositoryImpl.kt
  app/src/main/java/org/cardna/domain/repository/CardRepository.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/adapter/CardYouStoreRecyclerViewAdapter.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/TempCardYouStoreActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/viewmodel/CardPackViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/detailcard/view/DetailCardActivity.kt
  app/src/main/java/org/cardna/presentation/ui/setting/view/SecessionActivity.kt
  app/src/main/java/org/cardna/presentation/ui/setting/view/SettingActivity.kt
  app/src/main/java/org/cardna/presentation/ui/setting/viewmodel/SettingViewModel.kt
  app/src/main/java/org/cardna/presentation/util/LifeCycledValue.kt
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/activity_developer_info.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/activity_temp_card_you_store.xml
  app/src/main/res/layout/activity_version_info.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_cardyoustore.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: DaBin😎, Feature🖥, Layout, Complete

#45 [Feature] 소셜 로그인 세팅
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/data/local/Temp.kt
  app/src/main/java/org/cardna/data/local/sharedpref/CardnaSharedPreference.kt
  app/src/main/java/org/cardna/data/local/singleton/CardNaRepository.kt
  app/src/main/java/org/cardna/presentation/ui/detailcard/viewmodel/DetailCardViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/login/SplashActivity.kt
  app/src/main/res/layout/activity_detail_card.xml
  app/src/main/res/layout/activity_splash.xml
Labels: DaBin😎, Feature🖥

#46 [Feature] 카드나, 카드너 작성 구현
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/data/remote/api/card/CardService.kt
  app/src/main/java/org/cardna/data/remote/datasource/CardDataSource.kt
  app/src/main/java/org/cardna/data/remote/datasource/CardDataSourceImpl.kt
  app/src/main/java/org/cardna/data/remote/model/card/RequestCreateCardMeData.kt
  app/src/main/java/org/cardna/data/remote/model/card/RequestCreateCardYouData.kt
  app/src/main/java/org/cardna/data/remote/model/card/ResponseCardAllData.kt
  app/src/main/java/org/cardna/data/remote/model/card/ResponseCardMeData.kt
  app/src/main/java/org/cardna/data/remote/model/card/ResponseCardYouData.kt
  app/src/main/java/org/cardna/data/remote/model/card/ResponseCreateCardData.kt
  app/src/main/java/org/cardna/data/repository/CardRepositoryImpl.kt
  app/src/main/java/org/cardna/domain/repository/CardRepository.kt
  app/src/main/java/org/cardna/presentation/MainActivity.kt
  app/src/main/java/org/cardna/presentation/base/BaseViewUtil.kt
  app/src/main/java/org/cardna/presentation/di/RetrofitModule.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/adapter/CardPackMeRecyclerViewAdapter.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/BottomDialogImageFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardCreateActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardCreateCompleteActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardMeFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardPackFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardYouFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardYouStoreActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/FriendCardPackActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/OtherCardCreateCompleteActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/viewmodel/CardCreateViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/viewmodel/CardPackViewModel.kt
  app/src/main/res/drawable/bg_cardme.xml
  app/src/main/res/drawable/bg_cardyou.xml
  app/src/main/res/drawable/bg_cursor_color.xml
  app/src/main/res/drawable/bg_edittext_bottom_line.xml
  app/src/main/res/drawable/bg_main_black_radius_10dp.xml
  app/src/main/res/drawable/bg_main_green_radius_10dp.xml
  app/src/main/res/drawable/bg_white_3_1dp_radius_10dp.xml
  app/src/main/res/drawable/bg_white_3_radius_10dp.xml
  app/src/main/res/drawable/ic_selector_cardme_symbol_0.xml
  app/src/main/res/drawable/ic_selector_cardme_symbol_1.xml
  app/src/main/res/drawable/ic_selector_cardme_symbol_2.xml
  app/src/main/res/drawable/ic_selector_cardme_symbol_3.xml
  app/src/main/res/drawable/ic_selector_cardme_symbol_4.xml
  app/src/main/res/drawable/ic_selector_cardyou_symbol_0.xml
  app/src/main/res/drawable/ic_selector_cardyou_symbol_1.xml
  app/src/main/res/drawable/ic_selector_cardyou_symbol_2.xml
  app/src/main/res/drawable/ic_selector_cardyou_symbol_3.xml
  app/src/main/res/drawable/ic_selector_cardyou_symbol_4.xml
  app/src/main/res/layout/activity_card_create.xml
  app/src/main/res/layout/activity_card_create_complete.xml
  app/src/main/res/layout/activity_card_you_store.xml
  app/src/main/res/layout/activity_other_card_create_complete.xml
  app/src/main/res/layout/fragment_bottom_dialog_card.xml
  app/src/main/res/layout/fragment_bottom_dialog_image.xml
  app/src/main/res/layout/fragment_card_me.xml
  app/src/main/res/layout/fragment_card_pack.xml
  app/src/main/res/layout/fragment_card_you.xml
  app/src/main/res/layout/item_cardpack_cardme.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: help wanted, In Progress, Complete

#48 [HOTFIX] 대표카드 수정 index에러 해결
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardMeFragment.kt
  app/src/main/java/org/cardna/presentation/ui/editcard/adapter/EditCardAdapter.kt
  app/src/main/java/org/cardna/presentation/ui/editcard/adapter/EditCardDialogAdapter.kt
  app/src/main/java/org/cardna/presentation/ui/editcard/view/CardMeTabFragment.kt
  app/src/main/java/org/cardna/presentation/ui/editcard/view/CardYouTabFragment.kt
  app/src/main/java/org/cardna/presentation/ui/editcard/view/EditCardActivity.kt
  app/src/main/java/org/cardna/presentation/ui/editcard/view/EditCardDialogFragment.kt
  app/src/main/java/org/cardna/presentation/ui/editcard/viewmodel/EditCardDialogViewModel.kt
  app/src/main/res/drawable-v24/bg_green_null_black_radius_2.xml
  app/src/main/res/drawable-v24/bg_right_null_black_radius_2.xml
  app/src/main/res/layout/activity_edit_card.xml
  app/src/main/res/layout/fragment_main_card.xml
  app/src/main/res/layout/item_edit_card.xml
  app/src/main/res/layout/item_edit_card_dialog.xml
  app/src/main/res/layout/item_main_card_view.xml
Labels: bug, DaBin😎

#49 [FEAT] : 대표카드 수정뷰 구현 완료
  app/src/main/java/org/cardna/data/remote/api/card/CardService.kt
  app/src/main/java/org/cardna/data/remote/datasource/CardDataSource.kt
  app/src/main/java/org/cardna/data/remote/datasource/CardDataSourceImpl.kt
  app/src/main/java/org/cardna/data/repository/CardRepositoryImpl.kt
  app/src/main/java/org/cardna/domain/repository/CardRepository.kt
  app/src/main/java/org/cardna/presentation/ui/editcard/adapter/EditCardAdapter.kt
  app/src/main/java/org/cardna/presentation/ui/editcard/adapter/EditCardDialogAdapter.kt
  app/src/main/java/org/cardna/presentation/ui/editcard/view/CardMeTabFragment.kt
  app/src/main/java/org/cardna/presentation/ui/editcard/view/CardYouTabFragment.kt
  app/src/main/java/org/cardna/presentation/ui/editcard/view/EditCardActivity.kt
  app/src/main/java/org/cardna/presentation/ui/editcard/view/EditCardDialogFragment.kt
  app/src/main/java/org/cardna/presentation/ui/editcard/viewmodel/EditCardDialogViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/editcard/viewmodel/EditCardViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/view/MainCardActivity.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/view/MainCardFragment.kt
  app/src/main/java/org/cardna/presentation/util/ItemTouchHelperCallback.kt
  app/src/main/java/org/cardna/presentation/util/ItemTouchHelperListener.kt
  app/src/main/java/org/cardna/presentation/util/ViewExt.kt
  app/src/main/res/layout/activity_edit_card.xml
  app/src/main/res/layout/dialog_relation.xml
  app/src/main/res/layout/fragment_edit_card_dialog.xml
  build.gradle
Labels: Feature🖥, 🌈 JongChan

#52 [Feature] 카드나, 카드너 작성 구현 - 갤러리접근
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/presentation/MainActivity.kt
  app/src/main/java/org/cardna/presentation/base/BaseViewUtil.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/BottomDialogCardFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/BottomDialogImageFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardCreateActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardCreateCompleteActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardMeFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardPackFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardYouFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/FriendCardPackActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/OtherCardCreateCompleteActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/viewmodel/CardCreateViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/viewmodel/CardPackViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/view/MainCardActivity.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/view/MainCardFragment.kt
  app/src/main/res/layout/fragment_card_pack.xml
Labels: Complete
