Repository TeamCARDNA/Cardna-Android, pull requests merged in 2022-05, with the labels that each got.

#62 [ADD] #59 - 로그아웃, 탈퇴처리
  app/src/main/java/org/cardna/presentation/ui/setting/view/SecessionActivity.kt
  app/src/main/java/org/cardna/presentation/ui/setting/view/SettingActivity.kt
  app/src/main/java/org/cardna/presentation/ui/setting/viewmodel/SettingViewModel.kt
Labels: DaBin😎, Feature🖥, Complete

#67 [Feature] 카드나 보관함 구현 완료
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/TempCardYouStoreActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/viewmodel/CardPackViewModel.kt
  app/src/main/java/org/cardna/presentation/util/ViewExt.kt
  app/src/main/res/drawable/bg_cardyoustore_main_purple_darker_1_radius_45.xml
  app/src/main/res/drawable/ic_cardyoustore_copy.xml
  app/src/main/res/layout/activity_temp_card_you_store.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Feature🖥, Complete, 🌈 JongChan

#68 [Feature] 온보딩 추가, 회원가입 로직
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/CardNaApplication.kt
  app/src/main/java/org/cardna/data/local/singleton/CardNaRepository.kt
  app/src/main/java/org/cardna/data/remote/api/auth/AuthService.kt
  app/src/main/java/org/cardna/data/remote/model/auth/RequestSignUpData.kt
  app/src/main/java/org/cardna/data/remote/model/auth/ResponseSocialLoginData.kt
  app/src/main/java/org/cardna/data/remote/model/auth/ResponseTokenIssuanceData.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/LoginActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/OnBoardingActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/SetNameActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/SetNameFinishedActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/SplashActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/viewmodel/LoginViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/setting/view/PrivacyPolicyActivity.kt
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/activity_privacy_policy.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Feature🖥, 🌈 JongChan

#70 [Feature] push alarm 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/CardNaApplication.kt
  app/src/main/java/org/cardna/FirebaseMessagingService.kt
  app/src/main/java/org/cardna/data/local/singleton/CardNaRepository.kt
  app/src/main/java/org/cardna/presentation/MainActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/SplashActivity.kt
  app/src/main/res/drawable-hdpi/ic_stat_name.png
  app/src/main/res/drawable-mdpi/ic_stat_name.png
  app/src/main/res/drawable-xhdpi/ic_stat_name.png
  app/src/main/res/drawable-xxhdpi/ic_stat_name.png
  app/src/main/res/drawable-xxxhdpi/ic_stat_name.png
  app/src/main/res/drawable/ic_stat_app_settings_alt.png
  app/src/main/res/drawable/icon_simbol.png
Labels: In Progress, DaBin😎, Feature🖥

#71 [Hotfix] naver login
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/presentation/ui/login/view/LoginActivity.kt
Labels: DaBin😎, Complete

#72 [Feature] 네이버 로그인 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/data/local/singleton/CardNaRepository.kt
  app/src/main/java/org/cardna/data/remote/api/auth/AuthService.kt
  app/src/main/java/org/cardna/data/remote/datasource/AuthDataSource.kt
  app/src/main/java/org/cardna/data/remote/datasource/AuthDataSourceImpl.kt
  app/src/main/java/org/cardna/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/org/cardna/domain/repository/AuthRepository.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/LoginActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/SetNameActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/SplashActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/viewmodel/LoginViewModel.kt
  build.gradle
Labels: Minwoo🥺, Complete

#75 [Feature] 카드 이미지 공유
  .idea/gradle.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardMeFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardYouFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/viewmodel/CardCreateViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/viewmodel/CardPackViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/detailcard/view/CardShareActivity.kt
  app/src/main/java/org/cardna/presentation/ui/detailcard/view/DetailCardActivity.kt
  app/src/main/java/org/cardna/presentation/ui/detailcard/viewmodel/DetailCardViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/LoginActivity.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/res/drawable/ic_card_share.xml
  app/src/main/res/drawable/ic_card_share_save.xml
  app/src/main/res/layout/activity_card_share.xml
  app/src/main/res/layout/activity_other_card_create_complete.xml
  app/src/main/res/layout/fragment_card_me.xml
  app/src/main/res/layout/fragment_card_you.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: Minwoo🥺, Complete

#77 친구상태관리, 디자인 수정, 카드팩 포지션 저장
  .idea/gradle.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/data/remote/model/friend/ResponseSearchFriendCodeData.kt
  app/src/main/java/org/cardna/presentation/ui/alarm/adapter/WriteCardYouAdapter.kt
  app/src/main/java/org/cardna/presentation/ui/alarm/view/AlarmActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardPackFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/viewmodel/CardPackViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/detailcard/view/CardShareActivity.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/view/MainCardActivity.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/view/SearchFriendCodeActivity.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/org/cardna/presentation/util/BindingAdapter.kt
  app/src/main/res/layout/activity_main_card.xml
  app/src/main/res/layout/activity_search_friend_code.xml
  app/src/main/res/layout/fragment_main_card.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_alarm_friend_request.xml
  app/src/main/res/layout/item_alarm_write_cardyou.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: DaBin😎, Feature🖥, Complete

#80 푸시알림 데이터 로컬에서 저장 구현 및 알림, 상세페이지로 이동 분기
  app/src/main/java/org/cardna/FirebaseMessagingService.kt
  app/src/main/java/org/cardna/data/local/singleton/CardNaRepository.kt
  app/src/main/java/org/cardna/presentation/MainActivity.kt
  app/src/main/java/org/cardna/presentation/ui/alarm/adapter/FriendRequestAdapter.kt
  app/src/main/java/org/cardna/presentation/ui/alarm/view/AlarmActivity.kt
  app/src/main/java/org/cardna/presentation/ui/alarm/viewmodel/AlarmViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/view/MainCardFragment.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/adapter/MyPageFriendAdapter.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/setting/view/SettingActivity.kt
  app/src/main/java/org/cardna/presentation/ui/setting/viewmodel/SettingViewModel.kt
  app/src/main/java/org/cardna/presentation/util/DividerItemDecoration.kt
  app/src/main/java/org/cardna/presentation/util/SpaceItemDecoration.kt
  app/src/main/res/drawable-hdpi/img_logo.9.png
  app/src/main/res/drawable/bgbgbgbgbg.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_alarm_friend_request.xml
Labels: DaBin😎, Feature🖥, Complete

#82 Feature/6 kakao login
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/CardNaApplication.kt
  app/src/main/java/org/cardna/data/local/singleton/CardNaRepository.kt
  app/src/main/java/org/cardna/data/remote/api/auth/AuthService.kt
  app/src/main/java/org/cardna/data/remote/datasource/AuthDataSourceImpl.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/LoginActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/SplashActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/viewmodel/LoginViewModel.kt
  app/src/main/java/org/cardna/presentation/util/ViewExt.kt
Labels: Feature🖥, 🌈 JongChan

#86 카카오 성공
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/CardNaApplication.kt
  app/src/main/java/org/cardna/data/local/singleton/CardNaRepository.kt
  app/src/main/java/org/cardna/data/remote/api/auth/AuthService.kt
  app/src/main/java/org/cardna/data/remote/api/user/UserService.kt
  app/src/main/java/org/cardna/data/remote/datasource/AuthDataSourceImpl.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/LoginActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/SplashActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/viewmodel/LoginViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/setting/view/SecessionActivity.kt
  app/src/main/java/org/cardna/presentation/ui/setting/view/SettingActivity.kt
  app/src/main/java/org/cardna/presentation/ui/setting/viewmodel/SettingViewModel.kt
  app/src/main/java/org/cardna/presentation/util/AuthInterceptor.kt
Labels: DaBin😎, Feature🖥, Complete

#87 네이버 로그인, 재로그인
  app/src/main/java/org/cardna/data/remote/datasource/AuthDataSource.kt
  app/src/main/java/org/cardna/data/remote/datasource/AuthDataSourceImpl.kt
  app/src/main/java/org/cardna/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/org/cardna/domain/repository/AuthRepository.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/LoginActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/SplashActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/viewmodel/LoginViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/setting/view/SettingActivity.kt
Labels: DaBin😎, Feature🖥, Complete

#93 [Feature] 이미지 해상도 처리
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardCreateActivity.kt
  app/src/main/java/org/cardna/presentation/ui/detailcard/view/DetailCardActivity.kt
  app/src/main/res/layout/activity_detail_card.xml
Labels: DaBin😎, Feature🖥, Complete

#94 [FIX] MainFragment, MainActivity empty 뷰 수정
  app/build.gradle
  app/src/main/java/org/cardna/presentation/ui/maincard/view/MainCardActivity.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/view/MainCardFragment.kt
  app/src/main/res/layout/activity_main_card.xml
  app/src/main/res/layout/fragment_main_card.xml
Labels: Layout, Complete, 🌈 JongChan

#95 [Feature] 사진 해상도 처리 및 알림 점띄우기
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/ic_cardna_logo-playstore.png
  app/src/main/java/org/cardna/FirebaseMessagingService.kt
  app/src/main/java/org/cardna/data/local/singleton/CardNaRepository.kt
  app/src/main/java/org/cardna/presentation/MainActivity.kt
  app/src/main/java/org/cardna/presentation/ui/alarm/viewmodel/AlarmViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardCreateActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/FriendCardPackActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/viewmodel/CardCreateViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/detailcard/view/DetailCardActivity.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/view/MainCardFragment.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/viewmodel/MainCardViewModel.kt
  app/src/main/java/org/cardna/presentation/util/MultiPartResolver.kt
  app/src/main/java/org/cardna/presentation/util/ViewExt.kt
  app/src/main/res/drawable-mdpi/pop_up.9.png
  app/src/main/res/drawable/ic_cardna_logo_background.xml
  app/src/main/res/drawable/ic_icon_alert.xml
  app/src/main/res/layout/activity_detail_card.xml
  app/src/main/res/layout/activity_friend_card_pack.xml
  app/src/main/res/layout/activity_search_friend_code.xml
  app/src/main/res/layout/fragment_main_card.xml
  app/src/main/res/layout/item_alarm_write_cardyou.xml
  app/src/main/res/mipmap-anydpi-v26/ic_cardna_logo.xml
  app/src/main/res/mipmap-anydpi-v26/ic_cardna_logo_round.xml
  app/src/main/res/mipmap-hdpi/ic_cardna_logo.png
  app/src/main/res/mipmap-hdpi/ic_cardna_logo_foreground.png
  app/src/main/res/mipmap-hdpi/ic_cardna_logo_round.png
  app/src/main/res/mipmap-mdpi/ic_cardna_logo.png
  app/src/main/res/mipmap-mdpi/ic_cardna_logo_foreground.png
  app/src/main/res/mipmap-mdpi/ic_cardna_logo_round.png
  app/src/main/res/mipmap-xhdpi/ic_cardna_logo.png
  app/src/main/res/mipmap-xhdpi/ic_cardna_logo_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_cardna_logo_round.png
  app/src/main/res/mipmap-xxhdpi/ic_cardna_logo.png
  app/src/main/res/mipmap-xxhdpi/ic_cardna_logo_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_cardna_logo_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_cardna_logo.png
  app/src/main/res/mipmap-xxxhdpi/ic_cardna_logo_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_cardna_logo_round.png
  app/src/main/res/values/strings.xml
Labels: DaBin😎, Feature🖥, Complete

#96 [FIX] hotfix QA
  app/src/main/java/org/cardna/presentation/ui/editcard/view/CardMeTabFragment.kt
  app/src/main/java/org/cardna/presentation/ui/editcard/view/CardYouTabFragment.kt
  app/src/main/java/org/cardna/presentation/ui/editcard/view/EditCardActivity.kt
  app/src/main/java/org/cardna/presentation/ui/editcard/view/EditCardDialogFragment.kt
  app/src/main/java/org/cardna/presentation/ui/editcard/viewmodel/EditCardViewModel.kt
  app/src/main/java/org/cardna/presentation/util/SpaceItemDecoration.kt
  app/src/main/java/org/cardna/presentation/util/ViewExt.kt
  app/src/main/res/drawable-v24/bt_login_kakao.png
  app/src/main/res/drawable/bg_main_green_radius_8.xml
  app/src/main/res/drawable/bg_main_purple_radius_8.xml
  app/src/main/res/drawable/kakao_login_medium_wide.png
  app/src/main/res/layout/activity_edit_card.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main_card.xml
  app/src/main/res/layout/fragment_card_me_tab.xml
  app/src/main/res/layout/fragment_edit_card_dialog.xml
  app/src/main/res/layout/fragment_main_card.xml
  app/src/main/res/layout/item_edit_card_dialog.xml
  app/src/main/res/layout/item_main_card_view.xml
  app/src/main/res/values/strings.xml
Labels: bug, 🌈 JongChan

#100 [MOD] 온보딩 레이아웃 수정
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardCreateActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/SetNameActivity.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/res/layout/activity_card_create_complete.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_set_name.xml
  app/src/main/res/layout/activity_set_name_finished.xml
  app/src/main/res/layout/dialog_set_name.xml
  app/src/main/res/layout/fragment_first.xml
  app/src/main/res/layout/fragment_fourth.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_second.xml
  app/src/main/res/layout/fragment_third.xml
  app/src/main/res/values/strings.xml
Labels: DaBin😎, Complete

#102 [Feature] 카드너 추가 진입점에따른 분기, 알림 오류 해결
  app/src/main/java/org/cardna/presentation/base/BaseViewUtil.kt
  app/src/main/java/org/cardna/presentation/ui/alarm/adapter/WriteCardYouAdapter.kt
  app/src/main/java/org/cardna/presentation/ui/alarm/view/AlarmActivity.kt
  app/src/main/java/org/cardna/presentation/ui/alarm/viewmodel/AlarmViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardCreateCompleteActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardYouStoreActivity.kt
  app/src/main/java/org/cardna/presentation/ui/detailcard/view/DetailCardActivity.kt
  app/src/main/java/org/cardna/presentation/ui/detailcard/viewmodel/DetailCardViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/view/MainCardFragment.kt
  app/src/main/java/org/cardna/presentation/util/SpaceItemDecoration.kt
  app/src/main/res/layout/fragment_blind_area.xml
  app/src/main/res/layout/fragment_card_me_tab.xml
  app/src/main/res/layout/fragment_card_you_tab.xml
  app/src/main/res/layout/fragment_main_card.xml
  app/src/main/res/layout/fragment_open_area.xml
  app/src/main/res/layout/item_cardpack_cardme.xml
  app/src/main/res/layout/item_cardpack_cardyou.xml
  app/src/main/res/layout/item_edit_card.xml
  app/src/main/res/layout/item_edit_card_dialog.xml
  app/src/main/res/layout/item_main_card_view.xml
  app/src/main/res/values/strings.xml
Labels: DaBin😎, Complete

#108 hotfix #81
  app/src/main/java/org/cardna/presentation/ui/alarm/adapter/FriendRequestAdapter.kt
  app/src/main/java/org/cardna/presentation/ui/alarm/viewmodel/AlarmViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/SetNameFinishedActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/SplashActivity.kt
  app/src/main/java/org/cardna/presentation/ui/login/viewmodel/LoginViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/view/MainCardActivity.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/view/MainCardFragment.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/view/SearchFriendCodeActivity.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/org/cardna/presentation/util/ViewExt.kt
  app/src/main/res/anim/anim_translate_up_2560height.xml
  app/src/main/res/anim/fade_in.xml
  app/src/main/res/anim/fade_out.xml
  app/src/main/res/color/selector_dialog_confirm_btn_text.xml
  app/src/main/res/color/selector_go_to_cardpack_text.xml
  app/src/main/res/drawable-hdpi/_cardme.png
  app/src/main/res/drawable-hdpi/_cardyou.png
  app/src/main/res/drawable-hdpi/_insight.png
  app/src/main/res/drawable-hdpi/_maincard.png
  app/src/main/res/drawable-mdpi/_cardme.png
  app/src/main/res/drawable-mdpi/_cardyou.png
  app/src/main/res/drawable-mdpi/_insight.png
  app/src/main/res/drawable-mdpi/_maincard.png
  app/src/main/res/drawable-xhdpi/_cardme.png
  app/src/main/res/drawable-xhdpi/_cardyou.png
  app/src/main/res/drawable-xhdpi/_insight.png
  app/src/main/res/drawable-xhdpi/_maincard.png
  app/src/main/res/drawable-xxhdpi/_cardme.png
  app/src/main/res/drawable-xxhdpi/_cardyou.png
  app/src/main/res/drawable-xxhdpi/_insight.png
  app/src/main/res/drawable-xxhdpi/_maincard.png
  app/src/main/res/drawable-xxxhdpi/_cardme.png
  app/src/main/res/drawable-xxxhdpi/_cardyou.png
  app/src/main/res/drawable-xxxhdpi/_insight.png
  app/src/main/res/drawable-xxxhdpi/_maincard.png
  app/src/main/res/layout/activity_main_card.xml
  app/src/main/res/layout/activity_set_name_finished.xml
  app/src/main/res/layout/dialog_relation.xml
  app/src/main/res/layout/fragment_first.xml
  app/src/main/res/layout/fragment_fourth.xml
  app/src/main/res/layout/fragment_main_card.xml
  app/src/main/res/layout/fragment_second.xml
  app/src/main/res/layout/fragment_third.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 🌈 JongChan

#113 [HOTFIX] QA사항 반영 및 로딩 로티 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/presentation/ui/alarm/adapter/FriendRequestAdapter.kt
  app/src/main/java/org/cardna/presentation/ui/alarm/adapter/WriteCardYouAdapter.kt
  app/src/main/java/org/cardna/presentation/ui/alarm/view/AlarmActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardCreateActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardCreateCompleteActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardYouFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/FriendCardPackActivity.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/viewmodel/CardCreateViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/detailcard/view/DetailCardActivity.kt
  app/src/main/java/org/cardna/presentation/ui/detailcard/viewmodel/DetailCardViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/view/MainCardActivity.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/view/MainCardFragment.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/viewmodel/MainCardViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/view/SearchFriendCodeActivity.kt
  app/src/main/java/org/cardna/presentation/util/BindingAdapter.kt
  app/src/main/java/org/cardna/presentation/util/LottieUtil.kt
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/activity_card_create.xml
  app/src/main/res/layout/activity_detail_card.xml
  app/src/main/res/layout/activity_main_card.xml
  app/src/main/res/layout/activity_secession.xml
  app/src/main/res/layout/fragment_card_me.xml
  app/src/main/res/layout/fragment_main_card.xml
  app/src/main/res/layout/item_alarm_friend_request.xml
  app/src/main/res/layout/item_alarm_write_cardyou.xml
  app/src/main/res/values/strings.xml
Labels: DaBin😎, Feature🖥, Complete

#116 [HOTFIX] QA반영
  app/src/main/java/org/cardna/FirebaseMessagingService.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/view/CardMeFragment.kt
  app/src/main/java/org/cardna/presentation/ui/cardpack/viewmodel/CardCreateViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/login/view/SetNameActivity.kt
  app/src/main/java/org/cardna/presentation/ui/maincard/view/MainCardFragment.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/view/SearchFriendCodeActivity.kt
  app/src/main/java/org/cardna/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/org/cardna/presentation/ui/setting/view/SettingActivity.kt
  app/src/main/java/org/cardna/presentation/util/ViewExt.kt
  app/src/main/res/drawable/ic_icon_alert.xml
  app/src/main/res/layout/activity_search_friend_code.xml
  app/src/main/res/layout/fragment_main_card.xml
Labels: DaBin😎, Complete

#117 [FIX] padding 값 수정
  app/src/main/res/layout/activity_on_boarding.xml
Labels: Complete, 🌈 JongChan
